const actionTypes = Object.freeze({
  //app
  APP_START_UP_COMPLETE: "APP_START_UP_COMPLETE",
  SET_CONTENT_OF_CONFIRM_MODAL: "SET_CONTENT_OF_CONFIRM_MODAL",
  CHANGE_LANGUAGE: "CHANGE_LANGUAGE",

  //user
  ADD_USER_SUCCESS: "ADD_USER_SUCCESS",
  USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
  USER_LOGIN_FAIL: "USER_LOGIN_FAIL",
  PROCESS_LOGOUT: "PROCESS_LOGOUT",

  //admin
  FETCH_START_LOADING: "FETCH_START_LOADING",
  FETCH_GENDER_SUCCESS: "FETCH_GENDER_SUCCESS",
  FETCH_GENDER_FAILED: "FETCH_GENDER_FAILED",
  FETCH_ROLE_SUCCESS: "FETCH_ROLE_SUCCESS",
  FETCH_ROLE_FAILED: "FETCH_ROLE_FAILED",
  CREATE_USER_SUCCESS: "CREATE_USER_SUCCESS",
  CREATE_USER_FAILED: "CREATE_USER_FAILED",
  EDIT_USER_SUCCESS: "EDIT_USER_SUCCESS",
  EDIT_USER_FAILED: "EDIT_USER_FAILED",
  DELETE_USER_SUCCESS: "DELETE_USER_SUCCESS",
  DELETE_USER_FAILED: "DELETE_USER_FAILED",
  FETCH_ALL_USERS_SUCCESS: "FETCH_ALL_USERS_SUCCESS",
  FETCH_ALL_USERS_FAILED: "FETCH_ALL_USERS_FAILED",

  // CATEGORY
  CREATE_CATEGORY_SUCCESS: "CREATE_CATEGORY_SUCCESS",
  CREATE_CATEGORY_FAILED: "CREATE_CATEGORY_FAILED",
  EDIT_CATEGORY_SUCCESS: "EDIT_CATEGORY_SUCCESS",
  EDIT_CATEGORY_FAILED: "EDIT_CATEGORY_FAILED",
  DELETE_CATEGORY_SUCCESS: "DELETE_CATEGORY_SUCCESS",
  DELETE_CATEGORY_FAILED: "DELETE_CATEGORY_FAILED",
  FETCH_ALL_CATEGORIES_SUCCESS: "FETCH_ALL_CATEGORIES_SUCCESS",
  FETCH_ALL_CATEGORIES_FAILED: "FETCH_ALL_CATEGORIES_FAILED",

  // BRAND
  CREATE_BRAND_SUCCESS: "CREATE_BRAND_SUCCESS",
  CREATE_BRAND_FAILED: "CREATE_BRAND_FAILED",
  EDIT_BRAND_SUCCESS: "EDIT_BRAND_SUCCESS",
  EDIT_BRAND_FAILED: "EDIT_BRAND_FAILED",
  DELETE_BRAND_SUCCESS: "DELETE_BRAND_SUCCESS",
  DELETE_BRAND_FAILED: "DELETE_BRAND_FAILED",
  FETCH_ALL_BRANDS_SUCCESS: "FETCH_ALL_BRANDS_SUCCESS",
  FETCH_ALL_BRANDS_FAILED: "FETCH_ALL_BRANDS_FAILED",

  // DISCOUNT
  CREATE_DISCOUNT_SUCCESS: "CREATE_DISCOUNT_SUCCESS",
  CREATE_DISCOUNT_FAILED: "CREATE_DISCOUNT_FAILED",
  EDIT_DISCOUNT_SUCCESS: "EDIT_DISCOUNT_SUCCESS",
  EDIT_DISCOUNT_FAILED: "EDIT_DISCOUNT_FAILED",
  DELETE_DISCOUNT_SUCCESS: "DELETE_DISCOUNT_SUCCESS",
  DELETE_DISCOUNT_FAILED: "DELETE_DISCOUNT_FAILED",
  FETCH_ALL_DISCOUNTS_SUCCESS: "FETCH_ALL_DISCOUNTS_SUCCESS",
  FETCH_ALL_DISCOUNTS_FAILED: "FETCH_ALL_DISCOUNTS_FAILED",

  // PRODUCT
  CREATE_PRODUCT_SUCCESS: "CREATE_PRODUCT_SUCCESS",
  CREATE_PRODUCT_FAILED: "CREATE_PRODUCT_FAILED",
  EDIT_PRODUCT_SUCCESS: "EDIT_PRODUCT_SUCCESS",
  EDIT_PRODUCT_FAILED: "EDIT_PRODUCT_FAILED",
  DELETE_PRODUCT_SUCCESS: "DELETE_PRODUCT_SUCCESS",
  DELETE_PRODUCT_FAILED: "DELETE_PRODUCT_FAILED",
  FETCH_ALL_PRODUCTS_SUCCESS: "FETCH_ALL_PRODUCTS_SUCCESS",
  FETCH_ALL_PRODUCTS_FAILED: "FETCH_ALL_PRODUCTS_FAILED",
  FETCH_TOP_PRODUCTS_SUCCESS: "FETCH_TOP_PRODUCTS_SUCCESS",
  FETCH_TOP_PRODUCTS_FAILED: "FETCH_TOP_PRODUCTS_FAILED",
  FETCH_BRANDS_BY_CATEID_SUCCESS: "FETCH_BRANDS_BY_CATEID_SUCCESS",
  FETCH_BRANDS_BY_CATEID_FAILED: "FETCH_BRANDS_BY_CATEID_FAILED",

  // ORDER
  FETCH_STATUS_SUCCESS: "FETCH_STATUS_SUCCESS",
  FETCH_STATUS_FAILED: "FETCH_STATUS_FAILED",
  FETCH_PAYMENT_SUCCESS: "FETCH_PAYMENT_SUCCESS",
  FETCH_PAYMENT_FAILED: "FETCH_PAYMENT_FAILED",

  CREATE_ORDER_SUCCESS: "CREATE_ORDER_SUCCESS",
  CREATE_ORDER_FAILED: "CREATE_ORDER_FAILED",
  EDIT_ORDER_SUCCESS: "EDIT_ORDER_SUCCESS",
  EDIT_ORDER_FAILED: "EDIT_ORDER_FAILED",
  DELETE_ORDER_SUCCESS: "DELETE_ORDER_SUCCESS",
  DELETE_ORDER_FAILED: "DELETE_ORDER_FAILED",
  FETCH_ALL_ORDERS_SUCCESS: "FETCH_ALL_ORDERS_SUCCESS",
  FETCH_ALL_ORDERS_FAILED: "FETCH_ALL_ORDERS_FAILED",
});

export default actionTypes;
